server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /projets/avocat-affaires-site/ {
        alias /usr/share/nginx/html/projets/avocat-affaires-site/;
        try_files $uri $uri/ /projets/avocat-affaires-site/404.html;
    }

    location /projets/restaurant-etoile/ {
        alias /usr/share/nginx/html/projets/restaurant-etoile/;
        try_files $uri $uri/ /projets/restaurant-etoile/404.html;
    }

    location /projets/marathon-terre-lune/ {
        alias /usr/share/nginx/html/projets/marathon-terre-lune/;
        try_files $uri $uri/ /projets/marathon-terre-lune/404.html;
    }
}
